### ISSUE TITLE
Exiting program sometimes corrupts BASIC

### ISSUE THREAD

**Issue by jakebullet70** [neilsf/xc-basic3#177]
My file manager program. 
Load program, Q for quit and the do a LIST, You see the BASIC loader. 
Load program, T to tag file, Q for quit and the do a LIST, You see the BASIC loader is gone and machine is corrupt.

 
[diskmgr.zip](https://github.com/neilsf/xc-basic3/files/8549858/diskmgr.zip)

**Comment by neilsf** [comment]
It is easy to mangle the BASIC loader with a wrong `TEXTAT` command. For example `TEXTAT 0, 25, "anything"` will write to memory that's outside the screen RAM. But it can be `POKE`, `MEMSET`, anything that's writing to memory. Your program must make sure that memory operations are passed the correct parameters because the XC=BASIC runtime does guarantee memory safety.

**Comment by jakebullet70** [comment]
![image](https://user-images.githubusercontent.com/14124210/165318136-0cfe6ea7-e9ec-4aed-8bc2-e4a5708c3453.png)

**Comment by neilsf** [comment]
Okay it looks like XC=BASIC messes up important ZP locations. I'll try to fix that in a later release. For the time being you can try saving and restoring the ZP area that BASIC uses.
`MEMCPY 2, $C000, $8D` - at the beginning of your program
`MEMCPY $C000, 2, $8D` - at the end of your program, before the `END` statement
You can change `$C000` to any location of free space that your program doesn't use.

**Comment by jakebullet70** [comment]
I will wait for a fix. I have like 5 other places in my code that also causes corruption.

**Comment by JJFlash-IT** [comment]
Hello there :)
I believe I found out what gets corrupted and when, using VICE and its monitor (using `trace store address-range`).

What gets corrupted is the CHRGET routine in the zero-page, which is in the region $073-$8A (as the CBM Programmer's Reference Guide says). That's the routine that basically reads what has been typed after the READY prompt. So, you can type anything, even a non-valid syntax, usually a BRK occurs (like in the case of @jakebullet70 's program).

As for the culprit of this, I believe it's the `math/_fplib.asm` file, in the XCB library. Here, a number of symbols get defined which fall in the CHRGET range.

This is from the Symbols file that you can generate with Dasm while it assembles the PRG file:
```
ARG_LAST                 0073              (R )
ARGSIGN                  0074              (R )
SGNCPR                   0075              (R )
STRNG1                   0075              (R )
FACEXTENSION             0076              (R )
STRNG2                   0077              (R )
VARPNT                   0079                  
TEMP3                    007b              (R )
```
I've found that a few of these addresses, especially $76 (which is mapped to FACEXTENSION), get overwritten while using the float RND function, and/or multiplications that involve float numbers.

To reproduce the problem, this one-line program is a quick way of doing it:

`print rnd() * 14`

After compiling and running this, the random number is printed, and then anything you enter will be ignored, because a BRK is executed.

A workaround to that is:
```
memcpy $73, $c000, $17
print rnd() * 14
memcpy $c000, $73, $17
```
(it copies the CHRGET routine to $c000, and then restores it at the end of the program)

I also tested jakebullet's program, and did like he said to reproduce his problem, and I observed through the VICE monitor the same behaviour.

If you want more detail on this, how I got to these conclusions, go ahead and ask, I'll be happy to explain :) I learned as I was doing, and in the end it was a fun exploration.

**Comment by neilsf** [comment]
@JJFlash-IT yeah, that's exactly what's happening, thanks! I think I'll just reorganize the ZP addresses to leave CHRGET intact.
