### ISSUE TITLE
TYPE cannot contain fields starting with "next" (?)

### ISSUE THREAD

**Issue by orlof** [neilsf/xc-basic3#190]
```
TYPE Test
    nextx AS BYTE
END TYPE
```
`test.bas:2.10: syntax error near 'AS BYTE' in file test.bas in line 2`

**Comment by JJFlash-IT** [comment]
That's because it includes **do** which _is_ a reserved word  :)  (Try with "dodo", it happens as well)

I'm adding this only in the hope it helps diagnosing the problem: this also happens with `loopy`, but it doesn't happen with `forensic` nor with `whiley`, so it seems the error triggers with some but not all the reserved words used for loops.
