### ISSUE TITLE
IF statement fails with LEFT$ comparison

### ISSUE THREAD

**Issue by jakebullet70** [neilsf/xc-basic3#22]
![image](https://user-images.githubusercontent.com/14124210/147664306-9a768361-31f5-4c33-a375-6030b6357124.png)
[junk.zip](https://github.com/neilsf/xc-basic3/files/7788931/junk.zip)

**Comment by mrg-75** [comment]
I just did some quick testing, and if you swap the conditions around putting left$ on the left hand side of the equal sign, it works.

`if left$(searchme, len(findme)) = findme then` 

So the bug may be in how the if statement compares the condition on the right side, rather than with the result of the left$ function.
