### ISSUE TITLE
DASM?

### ISSUE THREAD

**Issue by BAHLZ** [neilsf/xc-basic3#255]
not sure what I am missing.

I unzipped the code, ran the exe under windows with the source and output but i get this error

** ERROR ** There has been an error while trying to execute DASM, please see the bellow message.
Tried to execute: "dasm.exe" "C:\Users\xxxxxxxxxxxxxxxxxx\AppData\Local\Temp\xcbtmp_F943EED8.asm" -o"comp.prg" -sC:\Users\xxxxxxxxxxxxxxxxxx\AppData\Local\Temp\xcbtmp_F943EED8.sym
'"dasm.exe"' is not recognized as an internal or external command,
operable program or batch file.

I don't see and DASM or anything referencing this file?

**Comment by neilsf** [comment]
It looks like your system can't find _dasm.exe_. Is it installed and added to the PATH?

Note: if you have downloaded dasm but you don't want to add it to the PATH environment variable, you have to specify the full path to _dasm.exe_ like this for example:

`xcbasic3.exe --dasm="C:\path\to\dasm.exe" infile.bas outfile.prg`

**Comment by BAHLZ** [comment]
Awesome, works great.

Is there a supporting IDE for XC-Basic you can recommend?

thanks!

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by neilsf** [comment]
There's a Visual Code plugin for XC=BASIC: https://marketplace.visualstudio.com/items?itemName=RealOrlof.orlof-xcbasic3

Or you can use any text editor. The ones I personally use are Geany and Textadept because they're easy to configure. They highlight BASIC source code very well and it is easy to add one-click compile commands.
