### ISSUE TITLE
FOR loop does not execute if end is expression greater than 255

### ISSUE THREAD

**Issue by orlof** [neilsf/xc-basic3#62]
e.g.
```
FOR t AS INT = 1 TO 128+128
    print t
NEXT t

```

**Comment by neilsf** [comment]
Not a bug.
The expression 128 + 128 is resolved as follows:
1) 128 is a BYTE
2) 128 is also a BYTE
3) Expression type therefore will be a BYTE
4) BYTE 128 + BYTE 128 = BYTE 0
5) 0 is converted to INT as t is an INT.
6) Loop is not executed as 1 < 0

**Comment by neilsf** [comment]
Try `FOR t AS INT = 1 TO 256` and it will work.

**Comment by orlof** [comment]
I thought about this a bit longer and my personal preference would be that constant expressions 
(CONST or literal) were calculated before type assignments.

I believe that the current behavior may be a potential source of errors e.g. I would like this to work
```
    CONST NUM_SPRITES = 15
    MEMSHIFT @sprite_data, $8000, NUM_SPRITES * 64
```

**Comment by neilsf** [comment]
> constant expressions
> (CONST or literal) were calculated before type assignments.

I absolutely agree but the compiler cannot (yet) calculate constant expressions.

Even if it could, think about the following situation:

      CONST CNUM_SPRITES = 15
      PRINT CNUM_SPRITES * 64 ' Would output 960
      
      DIM vnum_sprites AS BYTE
      vnum_sprites = 15
      PRINT vnum_sprites * 64 ' Would still output 192
  
The result is different just because the first identifier is a constant and the second one is a variable... very confusing.

I was also thinking about allowing integer size modifiers to literals, e. g `15I` is an INT, `15L` is a LONG, etc... but eventually dropped the idea because `CINT()` and `CLONG()` are there for the same purpose...
