### ISSUE TITLE
Question: STRING char encoding and C64 character ROM

### ISSUE THREAD

**Issue by orlof** [neilsf/xc-basic3#78]
```
DIM s AS STRING * 2
s = "aA"
print peek(@s+1), peek(@s+2)
```
Output: 65 193

In C64 character set 1: "a" = NA and "A" = 1
In C64 character set 2: "a" = 1 and "A" = 65

In ASCII "a" = 97 and "A" = 65

What encoding is used in XCBasic STRINGs and is there some easy way to convert STRING characters to C64 character set letters?

**Comment by neilsf** [comment]
Since the source code is in ASCII, the compiler tries to convert ASCII to PETSCII. If the ASCII character has a PETSCII equivalent, the PETSCII code will be used. Otherwise the ASCII code is left intact, usually causing to display something else on the C64.
Here is the conversion table:
https://github.com/neilsf/xc-basic3/blob/89718cfca27df83421e3108c1141dfdc683cde9f/source/compiler/petscii.d#L6

**Comment by orlof** [comment]
Thanks, seems that I was confused because I didn't realise there is another layer of conversion from PETSCII to screen codes.
